// <auto-generated />
using System;
using ForraControl.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForraControl.API.Migrations
{
    [DbContext(typeof(ForraDbContext))]
    [Migration("20260731174645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForraControl.API.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdPresentacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_presentacion");

                    b.Property<int>("IdVenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioEfectivo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_efectivo");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_detalles_venta");

                    b.HasIndex("IdPresentacion")
                        .HasDatabaseName("ix_detalles_venta_id_presentacion");

                    b.HasIndex("IdVenta")
                        .HasDatabaseName("ix_detalle_ventas_venta");

                    b.ToTable("detalles_venta", null, t =>
                        {
                            t.HasCheckConstraint("chk_detalle_ventas_cantidad", "cantidad > 0");
                        });
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.PrecioEspecial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdPresentacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_presentacion");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_especial");

                    b.HasKey("Id")
                        .HasName("pk_precios_especiales");

                    b.HasIndex("IdPresentacion")
                        .HasDatabaseName("ix_precios_especiales_id_presentacion");

                    b.HasIndex("IdCliente", "IdPresentacion")
                        .IsUnique()
                        .HasDatabaseName("uq_precios_especiales");

                    b.ToTable("precios_especiales", null, t =>
                        {
                            t.HasCheckConstraint("chk_precios_especiales_precio", "precio_especial >= 0");
                        });
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Presentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.Property<decimal>("Tamano")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tamano");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unidad");

                    b.HasKey("Id")
                        .HasName("pk_presentaciones");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("ix_presentaciones_producto");

                    b.HasIndex("Stock", "StockMinimo")
                        .HasDatabaseName("ix_presentaciones_stock")
                        .HasFilter("activo = true");

                    b.ToTable("presentaciones", null, t =>
                        {
                            t.HasCheckConstraint("chk_presentaciones_precio", "precio >= 0");

                            t.HasCheckConstraint("chk_presentaciones_stock", "stock >= 0");

                            t.HasCheckConstraint("chk_presentaciones_stock_minimo", "stock_minimo >= 0");
                        });
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Subcategoria")
                        .HasColumnType("text")
                        .HasColumnName("subcategoria");

                    b.Property<string>("Uso")
                        .HasColumnType("text")
                        .HasColumnName("uso");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_username");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("chk_usuarios_rol", "rol IN ('admin', 'trabajador')");
                        });
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Descuento")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("descuento");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("TotalFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_final");

                    b.Property<decimal>("TotalOriginal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_original");

                    b.HasKey("Id")
                        .HasName("pk_ventas");

                    b.HasIndex("Fecha")
                        .IsDescending()
                        .HasDatabaseName("ix_ventas_fecha");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_ventas_cliente");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_ventas_usuario");

                    b.ToTable("ventas", null, t =>
                        {
                            t.HasCheckConstraint("chk_ventas_descuento", "descuento >= 0");

                            t.HasCheckConstraint("chk_ventas_total_final", "total_final >= 0");
                        });
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.DetalleVenta", b =>
                {
                    b.HasOne("ForraControl.API.Models.Entities.Presentacion", "Presentacion")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdPresentacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalles_venta_presentaciones_id_presentacion");

                    b.HasOne("ForraControl.API.Models.Entities.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalles_venta_ventas_id_venta");

                    b.Navigation("Presentacion");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.PrecioEspecial", b =>
                {
                    b.HasOne("ForraControl.API.Models.Entities.Cliente", "Cliente")
                        .WithMany("PreciosEspeciales")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_precios_especiales_clientes_id_cliente");

                    b.HasOne("ForraControl.API.Models.Entities.Presentacion", "Presentacion")
                        .WithMany("PreciosEspeciales")
                        .HasForeignKey("IdPresentacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_precios_especiales_presentaciones_id_presentacion");

                    b.Navigation("Cliente");

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Presentacion", b =>
                {
                    b.HasOne("ForraControl.API.Models.Entities.Producto", "Producto")
                        .WithMany("Presentaciones")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_presentaciones_productos_id_producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Venta", b =>
                {
                    b.HasOne("ForraControl.API.Models.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ventas_clientes_id_cliente");

                    b.HasOne("ForraControl.API.Models.Entities.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ventas_usuarios_id_usuario");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Cliente", b =>
                {
                    b.Navigation("PreciosEspeciales");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Presentacion", b =>
                {
                    b.Navigation("DetallesVenta");

                    b.Navigation("PreciosEspeciales");
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Producto", b =>
                {
                    b.Navigation("Presentaciones");
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("ForraControl.API.Models.Entities.Venta", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
